### ISSUE TITLE
Install in cura

### ISSUE THREAD

**Issue by BEprints** [big-vl/GrizzlyManager#7]
Hi every time I try to install this to Cura it says invalid file type

**Comment by BEprints** [comment]
I've got it so show in Cura but it isn't doing anything no tower will load and no scripts come up under post processing

**Comment by big-vl** [comment]
> I've got it so show in Cura but it isn't doing anything no tower will load and no scripts come up under post processing

Have you made the correct path to the module? Do you have an empty folder first, and then the plugin itself?

**Comment by BEprints** [comment]
> 

I tried installing it the same way as every other plugin I have installed by dragging and dropping the file into Cura and I have also tried going into the folder where plugin are installed and putting the folder in there I have played around with different ways of installing it I would appear to be installed but nothing would show up in any menu. I gave up and installed Prusa Slicer but it would be grate of I can get it working for the future I will get some screen shots

**Comment by big-vl** [comment]
> > 
> 
> I tried installing it the same way as every other plugin I have installed by dragging and dropping the file into Cura and I have also tried going into the folder where plugin are installed and putting the folder in there I have played around with different ways of installing it I would appear to be installed but nothing would show up in any menu. I gave up and installed Prusa Slicer but it would be grate of I can get it working for the future I will get some screen shots

_How I got GrizzlyManager to work in Cura 5.2.1 on Windows. Perhaps it will be useful 
big_vl. Open the help/show configuration directory in the chicken, then the plugins folder. By analogy with other plugins, we create the GrizzlyManager folder and in it another GrizzlyManager folder and already transfer the contents of the archive from the github into it. Next, create the models folder and transfer all stl files of test models to it. Create a resources folder with a scripts folder in it. In both of them, I copied all the other files, because I don’t know exactly how to do it right. Restart Cura._


In one of the chats there was a method to run on windows

**Comment by BEprints** [comment]
> > > 
> > 
> > 
> > I tried installing it the same way as every other plugin I have installed by dragging and dropping the file into Cura and I have also tried going into the folder where plugin are installed and putting the folder in there I have played around with different ways of installing it I would appear to be installed but nothing would show up in any menu. I gave up and installed Prusa Slicer but it would be grate of I can get it working for the future I will get some screen shots
> 
> _How I got GrizzlyManager to work in Cura 5.2.1 on Windows. Perhaps it will be useful big_vl. Open the help/show configuration directory in the chicken, then the plugins folder. By analogy with other plugins, we create the GrizzlyManager folder and in it another GrizzlyManager folder and already transfer the contents of the archive from the github into it. Next, create the models folder and transfer all stl files of test models to it. Create a resources folder with a scripts folder in it. In both of them, I copied all the other files, because I don’t know exactly how to do it right. Restart Cura._
> 
> In one of the chats there was a method to run on windows

That worked would it be possible to set it up that way when downloaded so only one file needs to be copied into Cura plugins

**Comment by big-vl** [comment]
i have update github actions, close issue.
